c_stdlib:
- sysroot
c_stdlib_version:
- '2.17'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge mamba_dev
cxx_compiler:
- gxx
cxx_compiler_version:
- '12'
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
fmt:
- '10'
libarchive:
- '3.7'
libcurl:
- '8'
openssl:
- '3'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
pybind11_abi:
- '4'
python:
- 3.10.* *_cpython
python_impl:
- cpython
spdlog:
- '1.13'
target_platform:
- linux-armv7l
zip_keys:
- - c_stdlib_version
  - cdt_name
- - python
  - python_impl
zstd:
- '1.5'
